sudo: required
services:
  - docker
language: java
notifications:
    email: true
matrix:
  include:
    - jdk: openjdk8
before_install:
  - docker version
script: mvn clean package -B
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script:
    - echo 'Configuring GPG...'
    - echo ${GPG_SECRET_KEY} | base64 --decode | gpg --batch --import
    - mvn deploy --settings sonatype-settings.xml -DskipTests=true -Psign-artifacts -Dgpg.passphrase=${GPG_PASSPHRASE} -B
  skip_cleanup: true
  on:
    tags: true
