sudo: required

services:
  - docker

language: java

matrix:
  include:
    - jdk: openjdk8

branches:
  only:
    - master

before_install:
  - docker version

script: mvn clean verify -B

after_success:
  - bash <(curl -s https://codecov.io/bash)
